export APPLICATION_DIR="/Applications"
export DOCUMENT_DIR="$HOME/Documents"
export MOVIE_DIR="$HOME/Movies"
export IMAGE_DIR="$HOME/Photos"
export MUSIC_DIR="$HOME/Music"
export DOWNLOAD_DIR="$HOME/Downloads"
